version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: tour_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'tour'
      MYSQL_USER: 'tour'
      MYSQL_PASSWORD: 'tour'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: tour_redis
    ports:
      - "6379:6379"
    restart: always


  

